### ISSUE TITLE
Exceptions in Selecting the save directory on some devices

### ISSUE THREAD

**Issue by ytheekshana** [Domilopment/apk-extractor#1]
Hi. I was using your implementation to select the save directory & granting uri permissions. It works perfectly. But I get some crashes in on some devices. 

1. This is happening in the settings fragment. Android 10
`Fatal Exception: java.lang.SecurityException: No persistable permission grants found for UID 10235 and Uri content://com.android.providers.downloads.documents/tree/downloads [user 0]
       at android.os.Parcel.createException(Parcel.java:2071)
       at android.os.Parcel.readException(Parcel.java:2039)
       at android.os.Parcel.readException(Parcel.java:1987)
       at android.app.IUriGrantsManager$Stub$Proxy.takePersistableUriPermission(IUriGrantsManager.java:280)
       at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:2428)
       at com.test.myapplication.settings.SettingsFragment.takeUriPermission(SettingsFragment.java:48)
       at com.test.myapplication.settings.SettingsFragment.chooseSaveDir$lambda$1(SettingsFragment.java:33)
       at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3176)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2904)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:359)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
       at android.app.Activity.performStart(Activity.java:7892)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3326)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7399)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)` 

2. This is happening in the mustAskForSaveDir method on MainActivity. Android 11
`Fatal Exception: java.lang.IllegalArgumentException: Unknown authority com.android.externalstorage.documents
       at android.content.ContentResolver.call(ContentResolver.java:2402)
       at android.provider.DocumentsContract.findDocumentPath(DocumentsContract.java:1634)
       at com.test.myapplication.MainActivity.mustAskForSaveDir(MainActivity.kt:358)
       at com.test.myapplication.MainActivity.onStart(MainActivity.kt:318)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8024)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3499)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7703)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)`

3. This is happening in the takeUriPermission method on MainActivity. Android 10
`Fatal Exception: java.lang.SecurityException: No persistable permission grants found for UID 10801 and Uri content://com.android.providers.downloads.documents/tree/downloads [user 0]
       at android.os.Parcel.createException(Parcel.java:2088)
       at android.os.Parcel.readException(Parcel.java:2056)
       at android.os.Parcel.readException(Parcel.java:2004)
       at android.app.IUriGrantsManager$Stub$Proxy.takePersistableUriPermission(IUriGrantsManager.java:280)
       at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:2435)
       at com.ytheekshana.apkextractor.MainActivity.takeUriPermission(MainActivity.java:375)
       at com.ytheekshana.apkextractor.MainActivity.chooseSaveDir$lambda$6(MainActivity.java:335)
       at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
       at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.java:192)
       at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.kt:121)
       at android.app.Activity.dispatchActivityPostStarted(Activity.java:1278)
       at android.app.Activity.performStart(Activity.java:8018)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3580)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`

Can you please give an idea to fix these. Tried and still figuring a way. Thanks.

**Comment by Domilopment** [comment]
Hello Yasiru :)

I downloaded the Device Images for Pixel 2 API 29 & 30 and tested my App against it, but I could not reproduce the error messages.
When you say on some devices, can u become more specific, or provide me a way to test it, so I can throw some more logs in and try to get a better understanding of what is happening?

Further, when you say that your app is using my implementation, is it a modified version or copied over code, or do you use my applications code that is throwing these errors.
If it is modified in any form, maybe test if my app has also these bugs, and if not compare implementation differences.

For 2. there seems to be an error with resolving path for the persisted URI for the selected save path, u could check if the URI format is right, if the path exist (if it not exists, the function should not come to this point and return before) what should be fixed, or if there is an error in the implementation of DocumentContract.

For 1. and 3. it looks like a problem with requesting the Write or Read permission on these devices, something like after u selected over the Documents Tree dialog, there was no request for these permissions, or the flags in the result are missing

But all of this are speculations at this point and I would have to dig into it more, with more information ad hand about the code, the devices (maybe which manufacturer of these devices, ...) or anything other that could be relevant and maybe is playing into these problems

Best regards,
Dominic

**Comment by ytheekshana** [comment]
first of all, thanks for a wonderful app.  I copied only the directory saving codes, such as the creation of material alertdialgo in onStart(), chooseSaveDir(), mustAskForSaveDir(), takeUriPermission() and chooseDir & saveDir() in FileHelper. Didnt modified those. 

The 3rd one was occuring on Redmi Note 7, Redmi 9A, Redmi 8A, Galaxy J6. these devices were on firebase crashlytics. And it was 100% Android 10

**Comment by Domilopment** [comment]
Could you try to add Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION to chooseDir() addFlags?

**Comment by ytheekshana** [comment]
Did that and no luck

**Comment by Domilopment** [comment]
Ok :/
I found one person mentioning that adding
activity.grantUriPermission(activity.getPackageName(), uri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
Before the takePersistableUriPermission had helped

**Comment by Domilopment** [comment]
Another option to try is, replace
data.flags and (Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
With (Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)

**Comment by ytheekshana** [comment]
> Another option to try is, replace data.flags and (Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION) With (Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
> 
> https://developer.android.com/training/data-storage/shared/documents-files#persist-permissions (I think this could be the solution)

tried this. But looks like no luck. The first crash seems to be appearing again on Firebase. I will try your other solution and take a look soon.

**Comment by Domilopment** [comment]
I don't know if it changes something, but when you call
requireContext().applicationContext.contentResolver
You receive a different instance as with requireContext.contentResolver or requireActivity().contentResolver

**Comment by ytheekshana** [comment]
> Ok :/ I found one person mentioning that adding activity.grantUriPermission(activity.getPackageName(), uri, Intent.FLAG_GRANT_READ_URI_PERMISSION); Before the takePersistableUriPermission had helped

with this solution too I had no luck.

**Comment by ytheekshana** [comment]
> I don't know if it changes something, but when you call requireContext().applicationContext.contentResolver You receive a different instance as with requireContext.contentResolver or requireActivity().contentResolver

So if we use the application context on both the places, it might look positive right. Lets check that.

**Comment by Domilopment** [comment]
I changed some parts of the request save path flow and noticed, I could recreate the error message, when I call releasePersistableUriPermission on the uri that was previously selected and granted.
I fixed it with updating the if clause:
if(oldPath in cont... && oldPath != uri) ...

When you don't take the other changes I made, uri is equal to data.data!!

**Comment by ytheekshana** [comment]
I will take the other changes as well. Thanks for the fix,

**Comment by Domilopment** [comment]
You are welcome :)

The changes are in https://github.com/Domilopment/apk-extractor/commit/fd6866562304ec9fcbd4753f839634dd2e8b5566

Let me know if it fixed your crashes as well

**Comment by ytheekshana** [comment]
Previous Crashes dissappeared. Thanks. But this crash in on some devices. 

Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }

Is there a workaround other than checking if activity available?

**Comment by Domilopment** [comment]
Are these devices from Xaomi?

https://stackoverflow.com/questions/34021039/action-open-document-not-working-on-miui

**Comment by Domilopment** [comment]
Hello @edlei, thanks for reporting this.

This is most likely related to the device running Android TV (e.g. on a Xiaomi Stick), rather than standard Android on a phone or tablet.

The app currently relies on the Storage Access Framework (SAF) to let you choose a folder via the system file picker. On Android TV devices, this picker is often not available or not exposed to apps.

As a result, when the app tries to open the “select folder” dialog, nothing appears.

At the moment, Android TV devices were not considered during development, so this use case isn’t supported right now. Supporting it would likely require a fallback mechanism (e.g. using a fixed directory instead of a picker).

I can’t promise support yet, but I may look into adding a fallback in the future.

As a workaround, you maybe can use ADB to extract APKs directly from the device.
